package uniandes.fabricasw.ecotouring.core;
// Generated Mar 13, 2016 7:36:42 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conversation generated by hbm2java
 */
public class Conversation implements java.io.Serializable {

	private BigDecimal id;
	private Person person;
	private Conversation conversation;
	private Type type;
	private Item item;
	private String entry;
	private Date dateEntry;
	private Set conversations = new HashSet(0);

	public Conversation() {
	}

	public Conversation(BigDecimal id, Person person, Type type, Item item, String entry, Date dateEntry) {
		this.id = id;
		this.person = person;
		this.type = type;
		this.item = item;
		this.entry = entry;
		this.dateEntry = dateEntry;
	}

	public Conversation(BigDecimal id, Person person, Conversation conversation, Type type, Item item, String entry,
			Date dateEntry, Set conversations) {
		this.id = id;
		this.person = person;
		this.conversation = conversation;
		this.type = type;
		this.item = item;
		this.entry = entry;
		this.dateEntry = dateEntry;
		this.conversations = conversations;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Conversation getConversation() {
		return this.conversation;
	}

	public void setConversation(Conversation conversation) {
		this.conversation = conversation;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getEntry() {
		return this.entry;
	}

	public void setEntry(String entry) {
		this.entry = entry;
	}

	public Date getDateEntry() {
		return this.dateEntry;
	}

	public void setDateEntry(Date dateEntry) {
		this.dateEntry = dateEntry;
	}

	public Set getConversations() {
		return this.conversations;
	}

	public void setConversations(Set conversations) {
		this.conversations = conversations;
	}

}
