package uniandes.fabricasw.ecotouring.core;
// Generated Mar 13, 2016 7:36:42 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * ItemContent generated by hbm2java
 */
public class ItemContent implements java.io.Serializable {

	private BigDecimal id;
	private Item item;
	private String name;
	private String url;
	private String contentType;

	public ItemContent() {
	}

	public ItemContent(BigDecimal id, Item item, String name, String url, String contentType) {
		this.id = id;
		this.item = item;
		this.name = name;
		this.url = url;
		this.contentType = contentType;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

}
