package uniandes.fabricasw.ecotouring.core;
// Generated Mar 13, 2016 7:36:42 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {

	private BigDecimal id;
	private Person person;
	private Type type;
	private Date dateTransaction;
	private Set transacctionDetails = new HashSet(0);

	public Transaction() {
	}

	public Transaction(BigDecimal id, Person person, Type type, Date dateTransaction) {
		this.id = id;
		this.person = person;
		this.type = type;
		this.dateTransaction = dateTransaction;
	}

	public Transaction(BigDecimal id, Person person, Type type, Date dateTransaction, Set transacctionDetails) {
		this.id = id;
		this.person = person;
		this.type = type;
		this.dateTransaction = dateTransaction;
		this.transacctionDetails = transacctionDetails;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	public Date getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(Date dateTransaction) {
		this.dateTransaction = dateTransaction;
	}

	public Set getTransacctionDetails() {
		return this.transacctionDetails;
	}

	public void setTransacctionDetails(Set transacctionDetails) {
		this.transacctionDetails = transacctionDetails;
	}

}
