package uniandes.fabricasw.ecotouring.core;
// Generated Mar 20, 2016 12:10:37 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "TRANSACTION", schema = "ADMIN")
public class Transaction {

	private BigDecimal id;
	private Person person;
	private Type type;
	private Date dateTransaction;
	private Set<TransactionDetail> transacctionDetails = new HashSet<TransactionDetail>(0);

	public Transaction() {
	}

	public Transaction(BigDecimal id, Person person, Type type, Date dateTransaction) {
		this.id = id;
		this.person = person;
		this.type = type;
		this.dateTransaction = dateTransaction;
	}

	public Transaction(BigDecimal id, Person person, Type type, Date dateTransaction,
			Set<TransactionDetail> transacctionDetails) {
		this.id = id;
		this.person = person;
		this.type = type;
		this.dateTransaction = dateTransaction;
		this.transacctionDetails = transacctionDetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CUSTOMER", nullable = false)
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ESTATUS", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_TRANSACTION", nullable = false, length = 7)
	public Date getDateTransaction() {
		return this.dateTransaction;
	}

	public void setDateTransaction(Date dateTransaction) {
		this.dateTransaction = dateTransaction;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transaction")
	public Set<TransactionDetail> getTransacctionDetails() {
		return this.transacctionDetails;
	}

	public void setTransacctionDetails(Set<TransactionDetail> transacctionDetails) {
		this.transacctionDetails = transacctionDetails;
	}

}
