package uniandes.fabricasw.ecotouring.core;
// Generated Mar 13, 2016 7:36:42 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;

/**
 * TransacctionDetail generated by hbm2java
 */
public class TransacctionDetail implements java.io.Serializable {

	private BigDecimal id;
	private Transaction transaction;
	private Item item;
	private BigDecimal quantity;
	private BigDecimal price;

	public TransacctionDetail() {
	}

	public TransacctionDetail(BigDecimal id, Transaction transaction, Item item, BigDecimal quantity,
			BigDecimal price) {
		this.id = id;
		this.transaction = transaction;
		this.item = item;
		this.quantity = quantity;
		this.price = price;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Transaction getTransaction() {
		return this.transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	public BigDecimal getQuantity() {
		return this.quantity;
	}

	public void setQuantity(BigDecimal quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
